### PR TITLE
Add license header

### PR DESCRIPTION
**Pull request by skabashnyuk**
Fixes https://github.com/opentracing-contrib/java-web-servlet-filter/issues/46
As @pavolloffay  suggested  added header from https://github.com/opentracing/opentracing-java

### CODE REVIEW

**Comment by pavolloffay** [comment]
Thanks for a quick PR. But I mean to implement also a checking via plugin https://github.com/opentracing/opentracing-java/blob/master/pom.xml#L262.

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
Thanks @skabashnyuk, do you need a new release?

**Comment by skabashnyuk** [comment]
yes pleeese.

**Comment by pavolloffay** [comment]
0.2.1 is on the way

**Pull request merged**
